# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json pnpm-lock.yaml ./
RUN npm install --ignore-scripts

# Copy source code
COPY . .

# Expose default HTTP API port for Logseq if needed (not used by MCP)
# EXPOSE 12315

# Start the MCP server
CMD ["npx", "tsx", "index.ts"]
